- pipeline.id: audit_trail
  path.config: "/usr/share/logstash/pipeline/audittrail.conf"
  pipeline.workers: 1
- pipeline.id: audit_trail_deadletter
  path.config: "/usr/share/logstash/pipeline/deadletterpipeline.conf"
  pipeline.workers: 1